version: '3'
services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/app
    depends_on:
      - mongodb
    working_dir: /home/node/app
    links:
      - mongodb
    environment:
      ENCRYPTION_VECTOR: b62151909b045e08
      APP_PORT: 3000
    command: sh -c "yarn run test && yarn start"
  mongodb:
    image: mongo
